# Generated by Django 5.2.3 on 2025-10-17 03:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('event_type', models.CharField(choices=[('service', 'Culto'), ('meeting', 'Reunião'), ('study', 'Estudo Bíblico'), ('prayer', 'Oração'), ('visit', 'Visita'), ('other', 'Outro')], max_length=100)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('all_day', models.BooleanField(default=False)),
                ('color', models.CharField(blank=True, max_length=20, null=True)),
                ('reminder_minutes', models.IntegerField(blank=True, help_text='Minutos antes para lembrete', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'db_table': 'events',
                'ordering': ['start_datetime'],
            },
        ),
    ]
