# Generated by Django 5.2.3 on 2025-10-16 20:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('member_since', models.DateField(blank=True, null=True)),
                ('baptism_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('inactive', 'Inativo'), ('visitor', 'Visitante')], default='active', max_length=50)),
                ('ministry', models.CharField(blank=True, max_length=100, null=True)),
                ('cell_group', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Membro',
                'verbose_name_plural': 'Membros',
                'db_table': 'members',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='PastoralVisit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('visit_date', models.DateField()),
                ('visit_type', models.CharField(choices=[('routine', 'Rotina'), ('hospital', 'Hospital'), ('counseling', 'Aconselhamento'), ('emergency', 'Emergência'), ('other', 'Outro')], max_length=100)),
                ('notes', models.TextField(blank=True, null=True)),
                ('follow_up_needed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Visita Pastoral',
                'verbose_name_plural': 'Visitas Pastorais',
                'db_table': 'pastoral_visits',
                'ordering': ['-visit_date'],
            },
        ),
    ]
