# Generated by Django 5.2.3 on 2025-10-17 03:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BibleBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('abbrev', models.CharField(max_length=10)),
                ('testament', models.CharField(choices=[('old', 'Antigo Testamento'), ('new', 'Novo Testamento')], max_length=20)),
                ('book_order', models.IntegerField()),
                ('total_chapters', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Livro da Bíblia',
                'verbose_name_plural': 'Livros da Bíblia',
                'db_table': 'bible_books',
                'ordering': ['book_order'],
            },
        ),
        migrations.CreateModel(
            name='ReadingPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('plan_type', models.CharField(choices=[('daily', 'Diário'), ('weekly', 'Semanal'), ('custom', 'Personalizado')], max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('completed', 'Concluído'), ('paused', 'Pausado')], default='active', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Plano de Leitura',
                'verbose_name_plural': 'Planos de Leitura',
                'db_table': 'reading_plans',
            },
        ),
        migrations.CreateModel(
            name='ReadingPlanProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chapter', models.IntegerField()),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Progresso de Leitura',
                'verbose_name_plural': 'Progressos de Leitura',
                'db_table': 'reading_plan_progress',
            },
        ),
        migrations.CreateModel(
            name='VerseHighlight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('color', models.CharField(blank=True, choices=[('yellow', 'Amarelo'), ('green', 'Verde'), ('blue', 'Azul'), ('pink', 'Rosa'), ('purple', 'Roxo'), ('', 'Nenhum')], max_length=20, null=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Marcação de Versículo',
                'verbose_name_plural': 'Marcações de Versículos',
                'db_table': 'verse_highlights',
            },
        ),
        migrations.CreateModel(
            name='VerseNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Anotação de Versículo',
                'verbose_name_plural': 'Anotações de Versículos',
                'db_table': 'verse_notes',
            },
        ),
        migrations.CreateModel(
            name='BibleVerse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.IntegerField()),
                ('verse', models.IntegerField()),
                ('text', models.TextField()),
                ('version', models.CharField(choices=[('ACF', 'Almeida Corrigida Fiel'), ('ARA', 'Almeida Revista e Atualizada'), ('NVI', 'Nova Versão Internacional'), ('NTLH', 'Nova Tradução na Linguagem de Hoje'), ('NAA', 'Nova Almeida Atualizada'), ('KJV', 'King James Version')], default='ACF', max_length=10)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verses', to='bible.biblebook')),
            ],
            options={
                'verbose_name': 'Versículo',
                'verbose_name_plural': 'Versículos',
                'db_table': 'bible_verses',
                'ordering': ['book__book_order', 'chapter', 'verse'],
            },
        ),
    ]
