# Generated by Django 5.2.3 on 2025-10-16 20:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bible', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='readingplan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='readingplanprogress',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bible.biblebook'),
        ),
        migrations.AddField(
            model_name='readingplanprogress',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='bible.readingplan'),
        ),
        migrations.AddField(
            model_name='versehighlight',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verse_highlights', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='versehighlight',
            name='verse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='bible.bibleverse'),
        ),
        migrations.AddField(
            model_name='versenote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verse_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='versenote',
            name='verse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='bible.bibleverse'),
        ),
        migrations.AlterUniqueTogether(
            name='bibleverse',
            unique_together={('book', 'chapter', 'verse', 'version')},
        ),
        migrations.AlterUniqueTogether(
            name='versehighlight',
            unique_together={('user', 'verse')},
        ),
    ]
