# Generated by Django 5.2.3 on 2025-11-08 23:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bible', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingPlanTemplate',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('plan_type', models.CharField(choices=[('bible_year', 'Bíblia em 1 Ano'), ('nt_90days', 'Novo Testamento em 90 Dias'), ('psalms_month', 'Salmos em 1 Mês'), ('custom', 'Personalizado')], max_length=50)),
                ('duration_days', models.IntegerField()),
                ('icon', models.CharField(default='📖', max_length=10)),
                ('color', models.CharField(default='from-blue-500 to-blue-600', max_length=50)),
                ('readings_count', models.IntegerField()),
                ('readings_data', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Template de Plano',
                'verbose_name_plural': 'Templates de Planos',
                'db_table': 'reading_plan_templates',
            },
        ),
        migrations.CreateModel(
            name='UserReadingPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('plan_type', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_days', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('completed', 'Concluído'), ('paused', 'Pausado')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bible.readingplantemplate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_reading_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plano de Leitura do Usuário',
                'verbose_name_plural': 'Planos de Leitura dos Usuários',
                'db_table': 'user_reading_plans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReadingDay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('day_number', models.IntegerField()),
                ('readings_data', models.JSONField()),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('completed', 'Concluída'), ('skipped', 'Pulada')], default='pending', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_days', to='bible.userreadingplan')),
            ],
            options={
                'verbose_name': 'Dia de Leitura',
                'verbose_name_plural': 'Dias de Leitura',
                'db_table': 'reading_days',
                'ordering': ['date'],
                'unique_together': {('plan', 'date')},
            },
        ),
    ]
