# Generated by Django 5.2.3 on 2026-07-21 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bible', '0003_readingplantemplate_userreadingplan_readingday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bibleverse',
            name='version',
            field=models.CharField(choices=[('ALM1911', 'Almeida 1911 (Domínio Público)'), ('ACF', 'Almeida Corrigida Fiel'), ('ARA', 'Almeida Revista e Atualizada'), ('NVI', 'Nova Versão Internacional'), ('NTLH', 'Nova Tradução na Linguagem de Hoje'), ('NAA', 'Nova Almeida Atualizada'), ('KJV', 'King James Version')], default='ACF', max_length=10),
        ),
    ]
