# Generated by Django 5.2.3 on 2026-07-21 07:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Ex: CDB Banco Inter 2026', max_length=150)),
                ('investment_type', models.CharField(choices=[('cdb', 'CDB'), ('lci_lca', 'LCI/LCA'), ('tesouro_direto', 'Tesouro Direto'), ('poupanca', 'Poupança'), ('acoes', 'Ações'), ('fiis', 'Fundos Imobiliários'), ('fundos', 'Fundos de Investimento'), ('criptomoeda', 'Criptomoeda'), ('previdencia', 'Previdência Privada'), ('outro', 'Outro')], max_length=20)),
                ('institution', models.CharField(blank=True, max_length=100, null=True)),
                ('currency', models.CharField(default='BRL', help_text='Código ISO da moeda, ex: BRL, USD', max_length=3)),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=6, help_text='Cotação para BRL na data do aporte (apenas se moeda != BRL)', max_digits=12, null=True)),
                ('principal_amount', models.DecimalField(decimal_places=2, help_text='Valor aportado, na moeda do investimento', max_digits=12)),
                ('current_value', models.DecimalField(decimal_places=2, help_text='Valor atual, na moeda do investimento', max_digits=12)),
                ('rate_type', models.CharField(choices=[('prefixado', 'Prefixado (% a.a.)'), ('pos_cdi', 'Pós-fixado (% do CDI)'), ('pos_ipca', 'IPCA+'), ('sem_taxa', 'Sem taxa fixa (renda variável)')], default='sem_taxa', max_length=20)),
                ('rate_value', models.DecimalField(blank=True, decimal_places=2, help_text='Valor da taxa conforme rate_type, ex: 3.65 (% a.a.) ou 100 (% do CDI)', max_digits=6, null=True)),
                ('fees_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Taxa de administração/custódia, % a.a.', max_digits=5, null=True)),
                ('start_date', models.DateField()),
                ('maturity_date', models.DateField(blank=True, help_text='Vazio = sem vencimento definido', null=True)),
                ('liquidity', models.CharField(choices=[('daily', 'Liquidez diária'), ('at_maturity', 'Somente no vencimento')], help_text='Define se este valor conta como reserva financeira', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('redeemed', 'Resgatado')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Investimento',
                'verbose_name_plural': 'Investimentos',
                'db_table': 'investments',
                'ordering': ['-start_date'],
            },
        ),
    ]
