# Generated by Django 5.2.3 on 2025-06-30 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=100)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('bio', models.TextField(blank=True)),
                ('role', models.CharField(choices=[('pastor', 'Pastor'), ('leader', 'Líder'), ('member', 'Membro')], default='member', max_length=20)),
                ('church_name', models.CharField(blank=True, max_length=255)),
                ('church_location', models.CharField(blank=True, max_length=255)),
                ('ordination_date', models.DateField(blank=True, null=True)),
                ('ministerial_focus', models.CharField(blank=True, max_length=100)),
                ('theme', models.CharField(choices=[('light', 'Claro'), ('dark', 'Escuro')], default='light', max_length=10)),
                ('language', models.CharField(choices=[('pt-br', 'Português (Brasil)'), ('en', 'English'), ('es', 'Español')], default='pt-br', max_length=10)),
                ('verse_version_default', models.CharField(default='nvi', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_active_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
