# Generated by Django 5.2.3 on 2026-07-23 21:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleCalendarConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('google_email', models.EmailField(max_length=254)),
                ('scopes', models.CharField(blank=True, max_length=500)),
                ('access_token', models.TextField()),
                ('access_token_expires_at', models.DateTimeField()),
                ('refresh_token_encrypted', models.TextField()),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google_calendar_connection', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conexão com Google Calendar',
                'verbose_name_plural': 'Conexões com Google Calendar',
                'db_table': 'google_calendar_connections',
            },
        ),
    ]
