# Generated by Django 5.2.3 on 2025-10-10 01:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrayerRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('personal', 'Pessoal'), ('church', 'Igreja'), ('missions', 'Missões'), ('health', 'Saúde'), ('family', 'Família'), ('financial', 'Financeiro'), ('other', 'Outro')], max_length=100)),
                ('priority', models.CharField(choices=[('low', 'Baixa'), ('medium', 'Média'), ('high', 'Alta')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('answered', 'Respondido'), ('archived', 'Arquivado')], default='active', max_length=50)),
                ('is_confidential', models.BooleanField(default=False)),
                ('answered_date', models.DateField(blank=True, null=True)),
                ('answer_description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prayer_requests', to='members.member')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prayer_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pedido de Oração',
                'verbose_name_plural': 'Pedidos de Oração',
                'db_table': 'prayer_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
