# Generated by Django 5.2.3 on 2025-10-16 20:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Finance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('income', 'Entrada'), ('expense', 'Saída')], max_length=20)),
                ('category', models.CharField(choices=[('tithes', 'Dízimos'), ('offerings', 'Ofertas'), ('salaries', 'Salários'), ('utilities', 'Contas'), ('maintenance', 'Manutenção'), ('missions', 'Missões'), ('events', 'Eventos'), ('other', 'Outro')], max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_date', models.DateField()),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Dinheiro'), ('transfer', 'Transferência'), ('card', 'Cartão'), ('check', 'Cheque'), ('pix', 'PIX')], max_length=50, null=True)),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Finança',
                'verbose_name_plural': 'Finanças',
                'db_table': 'finances',
                'ordering': ['-transaction_date'],
            },
        ),
    ]
