# Generated by Django 5.2.3 on 2026-07-20 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='finance',
            name='group_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Agrupa as transações de uma mesma compra parcelada ou despesa fixa', null=True),
        ),
        migrations.AddField(
            model_name='finance',
            name='installment_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='finance',
            name='installment_total',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='finance',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
    ]
