# Generated by Django 5.2.3 on 2026-07-21 02:18

from django.db import migrations, models


def backfill_existing_as_confirmed(apps, schema_editor):
    """Registros lançados antes deste campo existir já aconteceram de fato — marca todos como confirmados."""
    Finance = apps.get_model('finances', 'Finance')
    Finance.objects.update(status='confirmed', confirmed_date=models.F('transaction_date'))


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0003_finance_group_id_finance_installment_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='finance',
            name='confirmed_date',
            field=models.DateField(blank=True, help_text='Data em que o pagamento/recebimento de fato ocorreu', null=True),
        ),
        migrations.AddField(
            model_name='finance',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('confirmed', 'Confirmado')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='finance',
            name='transaction_date',
            field=models.DateField(help_text='Data prevista/combinada (vencimento)'),
        ),
        migrations.RunPython(backfill_existing_as_confirmed, noop),
    ]
