# Generated by Django 5.2.3 on 2026-07-21 02:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bible', '0004_alter_bibleverse_version'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WritingTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Tag de Escrito',
                'verbose_name_plural': 'Tags de Escrito',
                'db_table': 'writing_tags',
            },
        ),
        migrations.CreateModel(
            name='Writing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('content', models.TextField(blank=True, null=True)),
                ('base_text', models.CharField(blank=True, help_text='Ex: João 3:16', max_length=100, null=True)),
                ('theme', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('completed', 'Concluído'), ('archived', 'Arquivado')], default='draft', max_length=50)),
                ('type', models.CharField(choices=[('sermao', 'Sermão'), ('devocional', 'Devocional'), ('esboco_estudo', 'Esboço de Estudo'), ('esboco_livro', 'Esboço de Livro')], default='sermao', max_length=30)),
                ('preached_date', models.DateField(blank=True, null=True)),
                ('estimated_duration', models.IntegerField(blank=True, help_text='Duração em minutos', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Escrito',
                'verbose_name_plural': 'Escritos',
                'db_table': 'writings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WritingVerse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_index', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bible.bibleverse')),
                ('writing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verses', to='writings.writing')),
            ],
            options={
                'verbose_name': 'Versículo do Escrito',
                'verbose_name_plural': 'Versículos do Escrito',
                'db_table': 'writing_verses',
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='WritingTagRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writing_relations', to='writings.writingtag')),
                ('writing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_relations', to='writings.writing')),
            ],
            options={
                'verbose_name': 'Relação Escrito-Tag',
                'verbose_name_plural': 'Relações Escrito-Tag',
                'db_table': 'writing_tag_relations',
                'unique_together': {('writing', 'tag')},
            },
        ),
    ]
