# Generated by Django 5.2.3 on 2025-10-10 01:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bible', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIInteraction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('interaction_type', models.CharField(choices=[('context', 'Contexto'), ('etymology', 'Etimologia'), ('related_texts', 'Textos Relacionados'), ('application', 'Aplicação')], max_length=50)),
                ('query', models.TextField()),
                ('response', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_interactions', to=settings.AUTH_USER_MODEL)),
                ('verse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_interactions', to='bible.bibleverse')),
            ],
            options={
                'verbose_name': 'Interação com IA',
                'verbose_name_plural': 'Interações com IA',
                'db_table': 'ai_interactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
