# Generated by Django 5.2.3 on 2025-10-16 20:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIInteraction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('interaction_type', models.CharField(choices=[('context', 'Contexto'), ('etymology', 'Etimologia'), ('related_texts', 'Textos Relacionados'), ('application', 'Aplicação')], max_length=50)),
                ('query', models.TextField()),
                ('response', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Interação com IA',
                'verbose_name_plural': 'Interações com IA',
                'db_table': 'ai_interactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
