# Generated by Django 5.2.3 on 2026-07-21 08:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aiinteraction',
            name='completion_tokens',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aiinteraction',
            name='model',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='aiinteraction',
            name='prompt_tokens',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aiinteraction',
            name='total_tokens',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='AIQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('free', 'Free'), ('pro', 'Pro'), ('unlimited', 'Unlimited')], default='free', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_quota', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cota de IA',
                'verbose_name_plural': 'Cotas de IA',
                'db_table': 'ai_quotas',
            },
        ),
    ]
