# Generated by Django 5.2.3 on 2026-07-21 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_aiinteraction_completion_tokens_aiinteraction_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiquota',
            name='stripe_customer_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='aiquota',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='aiquota',
            name='subscription_status',
            field=models.CharField(blank=True, choices=[('active', 'Ativa'), ('trialing', 'Em teste'), ('past_due', 'Pagamento atrasado'), ('canceled', 'Cancelada'), ('unpaid', 'Não paga')], default='', max_length=20),
        ),
    ]
