# Generated by Django 5.2.3 on 2026-07-21 23:33

import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.conf import settings
from django.db import migrations, models


def _create_vector_extension(apps, schema_editor):
    """CREATE EXTENSION só existe em Postgres. A tabela em si (abaixo) é
    criada em qualquer backend — inclusive SQLite, que aceita a coluna
    'vector(1536)' sem validar o tipo — pra que FKs com CASCADE de outros
    models (Writing, VerseNote, LibraryHighlight) continuem funcionando
    normalmente em dev local. A busca semântica de verdade (apps.ai.services)
    já checa `connection.vendor == 'postgresql'` antes de ler/escrever aqui."""
    if schema_editor.connection.vendor == 'postgresql':
        schema_editor.execute('CREATE EXTENSION IF NOT EXISTS vector;')


def _noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0004_aiquota_stripe_customer_id_and_more'),
        ('bible', '0004_alter_bibleverse_version'),
        ('library', '0002_initial'),
        ('writings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(_create_vector_extension, _noop),
        migrations.CreateModel(
            name='EmbeddingChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('writing', 'Escrito'), ('verse_note', 'Nota de Versículo'), ('library_highlight', 'Destaque de Biblioteca')], max_length=20)),
                ('chunk_index', models.PositiveIntegerField(default=0)),
                ('content', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1536)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('library_highlight', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='embedding_chunks', to='library.libraryhighlight')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embedding_chunks', to=settings.AUTH_USER_MODEL)),
                ('verse_note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='embedding_chunks', to='bible.versenote')),
                ('writing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='embedding_chunks', to='writings.writing')),
            ],
            options={
                'verbose_name': 'Pedaço de Embedding',
                'verbose_name_plural': 'Pedaços de Embedding',
                'db_table': 'ai_embedding_chunks',
            },
        ),
    ]
