# Generated by Django 5.2.3 on 2025-10-17 03:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sermon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('content', models.TextField(blank=True, null=True)),
                ('base_text', models.CharField(blank=True, help_text='Ex: João 3:16', max_length=100, null=True)),
                ('theme', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('completed', 'Concluído'), ('archived', 'Arquivado')], default='draft', max_length=50)),
                ('preached_date', models.DateField(blank=True, null=True)),
                ('estimated_duration', models.IntegerField(blank=True, help_text='Duração em minutos', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sermão',
                'verbose_name_plural': 'Sermões',
                'db_table': 'sermons',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SermonTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Tag de Sermão',
                'verbose_name_plural': 'Tags de Sermões',
                'db_table': 'sermon_tags',
            },
        ),
        migrations.CreateModel(
            name='SermonTagRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Relação Sermão-Tag',
                'verbose_name_plural': 'Relações Sermão-Tag',
                'db_table': 'sermon_tag_relations',
            },
        ),
        migrations.CreateModel(
            name='SermonVerse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_index', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Versículo do Sermão',
                'verbose_name_plural': 'Versículos dos Sermões',
                'db_table': 'sermon_verses',
                'ordering': ['order_index'],
            },
        ),
    ]
