# Generated by Django 5.2.3 on 2025-10-16 20:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bible', '0002_initial'),
        ('sermons', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sermon',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sermons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sermontagrelation',
            name='sermon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_relations', to='sermons.sermon'),
        ),
        migrations.AddField(
            model_name='sermontagrelation',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sermon_relations', to='sermons.sermontag'),
        ),
        migrations.AddField(
            model_name='sermonverse',
            name='sermon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verses', to='sermons.sermon'),
        ),
        migrations.AddField(
            model_name='sermonverse',
            name='verse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bible.bibleverse'),
        ),
        migrations.AlterUniqueTogether(
            name='sermontagrelation',
            unique_together={('sermon', 'tag')},
        ),
    ]
