# Generated by Django 5.2.3 on 2025-10-17 03:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('reminder', 'Lembrete'), ('deadline', 'Prazo'), ('info', 'Informação'), ('warning', 'Aviso'), ('success', 'Sucesso')], max_length=50)),
                ('is_read', models.BooleanField(default=False)),
                ('related_entity_type', models.CharField(blank=True, choices=[('goal', 'Meta'), ('event', 'Evento'), ('prayer', 'Oração'), ('sermon', 'Sermão'), ('member', 'Membro'), ('other', 'Outro')], max_length=50, null=True)),
                ('related_entity_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
