# Generated by Django 5.2.3 on 2026-07-21 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='related_entity_type',
            field=models.CharField(blank=True, choices=[('goal', 'Meta'), ('event', 'Evento'), ('prayer', 'Oração'), ('writing', 'Escrito'), ('member', 'Membro'), ('other', 'Outro')], max_length=50, null=True),
        ),
    ]
